export const data = [
  {
    id: 1,
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2e/.com_logo.png",
    title: "The TLD",
    description:
      "Does the domain extension math the language of the domain name?",
  },
  {
    id: 2,
    logo: "https://www.svgrepo.com/show/115430/ruler.svg",
    title: "Domain Length",
    description: "Is the domain short enough to remember?",
  },
  {
    id: 3,
    logo: "https://www.svgrepo.com/show/343134/globe.svg",
    title: "Language",
    description: "How complex is the actual domain name?",
  },
  {
    id: 4,
    logo: "https://www.svgrepo.com/show/88914/circular-label-with-certified-stamp.svg",
    title: "International recognition",
    description: "Can the domain name be used on an international scale?",
  },
  {
    id: 5,
    logo: "https://www.svgrepo.com/show/14071/search.svg",
    title: "Search engine",
    description: "Does the domain follow search engine guidelines?",
  },
  {
    id: 6,
    logo: "https://www.svgrepo.com/show/211490/megaphone-speaker.svg",
    title: "Advertising Potential",
    description: "Could the domain be used for advertising campaigns?",
  },
  {
    id: 7,
    logo: "https://www.svgrepo.com/show/34984/settings.svg",
    title: "Sales Oppurtunities",
    description: "Can the domain name be used on an international scale?",
  },
  {
    id: 8,
    logo: "https://www.svgrepo.com/show/347535/t-box.svg",
    title: "Typo susceptibility",
    description: "How high is the risk of mistyping the domain name?",
  },
  {
    id: 9,
    logo: "https://www.svgrepo.com/show/199111/light-bulb-idea.svg",
    title: "Business potential",
    description: "Can the domain be used as your company address?",
  },
];

export const cards = [
  {
    id: 1,
    version: "3.3.0",
    date: "14/05/2018",
    buttonType: "New",
    name: "Kevin Joe",
    text: "File system changed from Dokan to CBFS Host Cloud Drive is now a network drive various bug fixes and stability improvements Share permissions re-design and optimization",
    color: "green",
  },
  {
    id: 2,
    version: "3.1.0",
    date: "20/05/2015",
    buttonType: "Fix",
    name: "Kevin Joe",
    text: "Introduction Host Cloud Drive - virtual drive functionality New Share options and management New, more user friendly design Sync optimizations Various performance improvements and bug fixes",
    color: "blue",
  },
  {
    id: 3,
    version: "3.1.0",
    date: "20/05/2015",
    buttonType: "Improvement",
    name: "Kevin Joe",
    text: "Added Settings for Auto Start Added Update Notification Speed Optimization Bug Fixes",
    color: "purple",
  },
  {
    id: 4,
    version: "3.1.0",
    date: "14/05/2018",
    buttonType: "Fix",
    name: "Kevin Joe",
    text: "File system changed from Dokan to CBFS Host Cloud Drive is now a network drive various bug fixes and stability improvements Share permissions re-design and optimization",
    color: "green",
  },
  {
    id: 5,
    version: "3.1.0",
    date: "20/05/2015",
    buttonType: "New",
    name: "Kevin Joe",
    text: "Introduction Host Cloud Drive - virtual drive functionality New Share options and management New, more user friendly design Sync optimizations Various performance improvements and bug fixes",
    color: "blue",
  },
  {
    id: 6,
    version: "3.1.0",
    date: "20/05/2015",
    buttonType: "Improvement",
    name: "Kevin Joe",
    text: "Added Settings for Auto Start Added Update Notification Speed Optimization Bug Fixes",
    color: "purple",
  },
  {
    id: 7,
    version: "3.1.0",
    date: "14/05/2018",
    buttonType: "Fix",
    name: "Kevin Joe",
    text: "File system changed from Dokan to CBFS Host Cloud Drive is now a network drive various bug fixes and stability improvements Share permissions re-design and optimization",
    color: "green",
  },
  {
    id: 8,
    version: "3.1.0",
    date: "20/05/2015",
    buttonType: "New",
    name: "Kevin Joe",
    text: "Introduction Host Cloud Drive - virtual drive functionality New Share options and management New, more user friendly design Sync optimizations Various performance improvements and bug fixes",
    color: "blue",
  },
  {
    id: 9,
    version: "3.1.0",
    date: "20/05/2015",
    buttonType: "Improvement",
    name: "Kevin Joe",
    text: "Added Settings for Auto Start Added Update Notification Speed Optimization Bug Fixes",
    color: "purple",
  },
];
